import { Inter } from "next/font/google";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "S V Scientific | About",
	description: "Generated by create next app",
};

export default function Layout({ children }) {
	return (
		<>
			{/* <Navbar /> */}
			{children}
			{/* <Footer /> */}
		</>
	);
}
